site_name: Fit
docs_dir: doc/src
site_dir: doc/html/
repo_url: https://github.com/pfultz2/Fit
use_directory_urls: false
extra_javascript: [js/configure.js]
pages:
- ['index.md', 'Home']
# About
- ['quickstart.md', 'About', 'Quick Start']
- ['concepts.md', 'About', 'Basic Concepts']
- ['requirements.md', 'About', 'Requirements']
- ['acknowledgements.md', 'About', 'Acknowledgements']
- ['license.md', 'About', 'License']
# Adaptors
- ['by.md', 'Adaptors', 'by']
- ['compose.md', 'Adaptors', 'compose']
- ['conditional.md', 'Adaptors', 'conditional']
- ['compress.md', 'Adaptors', 'compress']
- ['fix.md', 'Adaptors', 'fix']
- ['flip.md', 'Adaptors', 'flip']
- ['flow.md', 'Adaptors', 'flow']
- ['implicit.md', 'Adaptors', 'implicit']
- ['indirect.md', 'Adaptors', 'indirect']
- ['infix.md', 'Adaptors', 'infix']
- ['lazy.md', 'Adaptors', 'lazy']
- ['match.md', 'Adaptors', 'match']
- ['mutable.md', 'Adaptors', 'mutable']
- ['partial.md', 'Adaptors', 'partial']
- ['pipable.md', 'Adaptors', 'pipable']
- ['protect.md', 'Adaptors', 'protect']
- ['result.md', 'Adaptors', 'result']
- ['reveal.md', 'Adaptors', 'reveal']
- ['reverse_compress.md', 'Adaptors', 'reverse_compress']
- ['static.md', 'Adaptors', 'static']
- ['unpack.md', 'Adaptors', 'unpack']
- ['variadic.md', 'Adaptors', 'variadic']
# Functions
- ['always.md', 'Functions', 'always']
- ['args.md', 'Functions', 'args']
- ['construct.md', 'Functions', 'construct']
- ['identity.md', 'Functions', 'identity']
- ['placeholders.md', 'Functions', 'placeholders']
# Utilities
- ['apply.md', 'Utilities', 'apply']
- ['apply_eval.md', 'Utilities', 'apply_eval']
- ['capture.md', 'Utilities', 'capture']
- ['eval.md', 'Utilities', 'eval']
- ['function.md', 'Utilities', 'FIT_STATIC_FUNCTION']
- ['lambda.md', 'Utilities', 'FIT_STATIC_LAMBDA']
- ['lift.md', 'Utilities', 'lift']
- ['is_callable.md', 'Utilities', 'is_callable']
- ['pack.md', 'Utilities', 'pack']
- ['returns.md', 'Utilities', 'returns']
- ['tap.md', 'Utilities', 'tap']
